name = "EnergyModelsInvestments"
uuid = "fca3f8eb-b383-437d-8e7b-aac76bb2004f"
authors = ["Lars Hellemo <Lars.Hellemo@sintef.no>, Dimitri Pinel <Dimitri.Pinel@sintef.no>"]
version = "0.4.0"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
EnergyModelsGeography = "3f775d88-a4da-46c4-a2cc-aa9f16db6708"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
EnergyModelsGeography = "3f775d88-a4da-46c4-a2cc-aa9f16db6708"

[extensions]
EMIGeoExt = "EnergyModelsGeography"

[compat]
EnergyModelsBase = "^0.5.0"
EnergyModelsGeography = "^0.7.0"
JuMP = "1.5"
julia = "^1.9"
TimeStruct = "^0.6.0"